#Load packspeciess
library(tidyverse)

#Let's quickly rename it to make things less messy

ts <- triton.trim2

#Add a new column with the title ecogroup

ts["ecogroup"] <- NA

for (i in 1:(nrow(ts))) {
    	if (ts$species[i] == "Acarinina africana") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina alticonica") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina angulosa") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina aspensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina boudreauxi") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina bullbrooki") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina coalingensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina collactea") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina cuneicamerata") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina echinata") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina esnaensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina esnehensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina interposita") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina mcgowrani") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina mckannai") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina medizzai") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina nitida") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina pentacamerata") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina praetopilensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina primitiva") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina pseudosubsphaerica") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina pseudotopilensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina punctocarinata") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina quetra") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina rohri") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina sibaiyaensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina soldadoensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina strabocella") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina subsphaerica") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina topilensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Acarinina wilcoxensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Alicantina lozanoi") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Astrorotalia palmerae") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Beella digitata") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Beella digitata") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Beella megastoma") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Beella praedigitata") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Berggrenia pumilio") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Candeina nitida") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Cassigerinella chipolensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Cassigerinella eocaenica") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Cassigerinelloita amekiensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Catapsydrax africanus") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Catapsydrax dissimilis") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Catapsydrax globiformis") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Catapsydrax howei") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Catapsydrax parvulus") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Catapsydrax unicavus") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Chiloguembelina crinita") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Chiloguembelina cubensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Chiloguembelina midwayensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Chiloguembelina morsei") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Chiloguembelina ototara") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Chiloguembelina parallela") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Chiloguembelina subtriangularis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Chiloguembelina trinitatensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Chiloguembelina wilcoxensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Ciperoella angulisuturalis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Ciperoella ciperoensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Clavatorella bermudezi") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Clavigerinella akersi") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Clavigerinella caucasica") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Clavigerinella colombiana") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Clavigerinella eocanica") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Clavigerinella jarvisi") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Cribrohantkenina inflata") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Dentigloborotalia anfracta") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Dentoglobigerina altispira") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Dentoglobigerina baroemoenensis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Dentoglobigerina binaiensis") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Dentoglobigerina galavisi") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Dentoglobigerina globosa") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Dentoglobigerina globularis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Dentoglobigerina juxtabinaiensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Dentoglobigerina larmeui") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Dentoglobigerina prasaepis") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Dentoglobigerina pseudovenezuelana") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Dentoglobigerina rohri") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Dentoglobigerina sellii") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Dentoglobigerina sp") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Dentoglobigerina tapuriensis") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Dentoglobigerina tripartita") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Dentoglobigerina venezuelana") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Dipsidripella danvillensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Eoglobigerina edita") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Eoglobigerina eobulloides") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Eoglobigerina spiralis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Fohsella fohsi") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Fohsella lenguaensis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Fohsella lobata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Fohsella paralenguaensis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Fohsella peripheroacuta") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Fohsella peripheroronda") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Fohsella praefohsi") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Fohsella robusta") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globanomalina archeocompressa") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globanomalina australiformis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globanomalina chapmani") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globanomalina compressa") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globanomalina ehrenbergi") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globanomalina imitata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globanomalina luxorensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globanomalina ovalis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globanomalina planocompressa") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globanomalina planoconica") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globanomalina pseudomenardii") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globigerina bulloides") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globigerina eamesi") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerina falconensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerina officinalis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerina umbilicata") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinatella insueta") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Globigerinatella sp.") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Globigerinatheka barri") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinatheka curryi") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinatheka euganea") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinatheka index") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinatheka korotkovi") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinatheka kugleri") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinatheka luterbacheri") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinatheka mexicana") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinatheka semiinvoluta") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinatheka subconglobata") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinatheka tropicalis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinella adamsi") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Globigerinella calida") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globigerinella navazuelensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Globigerinella obesa") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globigerinella praesiphonifera") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globigerinella radians") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Globigerinella siphonifera") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globigerinita glutinata") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Globigerinita minuta") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Globigerinita parkerae") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Globigerinita uvula") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Globigerinoides altiapertura") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoides conglobatus") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoides diminutus") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoides elongatus") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Globigerinoides extremus") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoides mitra") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoides obliquus") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoides parawoodi") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoides ruber") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoides ruber (pink)") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoides ruber (white)") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoides seigliei") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoides subquadratus") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globigerinoidesella fistulosa") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globoconella conoidea") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globoconella conomiozea") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globoconella inflata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globoconella miozea") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globoconella pliozea") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globoconella puncticulata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globoconella sphericomiozea") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globoconella terminalis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globoconusa daubjergensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Globoquadrina conglomerata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globoquadrina dehiscens") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globorotalia flexuosa") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globorotalia merotumida") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globorotalia plesiotumida") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globorotalia tumida") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globorotalia ungulata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globorotalia zealandica") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Globorotaloides eovariabilis") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Globorotaloides hexagonus") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Globorotaloides quadrocameratus") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Globorotaloides stainforthi") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Globorotaloides suteri") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Globorotaloides testarugosa") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Globorotaloides variabilis") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Globoturborotalita anguliofficinalis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globoturborotalita apertura") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globoturborotalita bassriverensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globoturborotalita bollii") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globoturborotalita brazieri") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globoturborotalita cancellata") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Globoturborotalita connecta") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globoturborotalita decoraperta") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globoturborotalita druryi") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globoturborotalita euapertura") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Globoturborotalita gnaucki") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globoturborotalita kennetti") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globoturborotalita labiacrassata") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globoturborotalita martini") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globoturborotalita nepenthes") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globoturborotalita occlusa") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globoturborotalita ouachitaensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Globoturborotalita rubescens") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globoturborotalita tenella") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Globoturborotalita woodi") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Guembelitria cretacea") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Guembelitrioides nuttalli") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Hantkenina alabamensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Hantkenina australis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Hantkenina compressa") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Hantkenina dumblei") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Hantkenina lehneri") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Hantkenina liebusi") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hantkenina mexicana") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hantkenina nanggulanensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Hantkenina primitiva") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Hantkenina singanoae") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Hastigerina pelagica") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Hirsutella bermudezi") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella challengeri") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella cibaoensis") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella evoluta") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella gigantea") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella hirsuta") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella juanai") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella margaritae") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella praemargaritae") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella praescitula") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella primitiva") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella scitula") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Hirsutella theyeri") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Igorina albeari") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Igorina pusilla") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Igorina tadjikistanensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Jenkinsina triseriata") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Menardella archeomenardii") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Menardella exilis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Menardella fimbriata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Menardella limbata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Menardella menardii") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Menardella miocenica") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Menardella multicamerata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Menardella pertenuis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Menardella praemenardii") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Menardella pseudomiocenica") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Morozovella acuta") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella acutispira") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella aequa") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella allisonensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella angulata") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella apanthesma") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella aragonensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella caucasica") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella conicotruncata") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella crater") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella edgari") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella formosa") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella gracilis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella lensiformis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella marginodentata") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella occlusa") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella pasionensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella praeangulata") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella subbotinae") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovella velascoensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovelloides bandyi") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovelloides coronatus") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovelloides crassatus") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Morozovelloides lehneri") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Muricohedbergella holmdelensis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Muricohedbergella monmouthensis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Mutabella mirabilis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Neogloboquadrina acostaensis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Neogloboquadrina dutertrei") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Neogloboquadrina humerosa") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Neogloboquadrina incompta") ts$ecogroup[i] <- "5" else
    	if (ts$species[i] == "Neogloboquadrina pachyderma") ts$ecogroup[i] <- "5" else
    	if (ts$species[i] == "Orbulina suturalis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Orbulina universa") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Orbulinoides beckmanni") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Orcadia riedeli") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Paragloborotalia acrostoma") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Paragloborotalia bella") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Paragloborotalia birnageae") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Paragloborotalia continuosa") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Paragloborotalia griffinoides") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Paragloborotalia incognita") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Paragloborotalia kugleri") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Paragloborotalia mayeri") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Paragloborotalia nana") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Paragloborotalia opima") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Paragloborotalia pseudocontinuosa") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Paragloborotalia pseudokugleri") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Paragloborotalia semivera") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Paragloborotalia siakensis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Parasubbotina aff_pseudobulloides") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Parasubbotina eoclava") ts$ecogroup[i] <- "6" else
    	if (ts$species[i] == "Parasubbotina griffinae") ts$ecogroup[i] <- "6" else
    	if (ts$species[i] == "Parasubbotina hagni") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Parasubbotina inaequispira") ts$ecogroup[i] <- "6" else
    	if (ts$species[i] == "Parasubbotina prebetica") ts$ecogroup[i] <- "6" else
    	if (ts$species[i] == "Parasubbotina pseudobulloides") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Parasubbotina pseudowilsoni") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Parasubbotina varianta") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Parasubbotina variospira") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Parvularugoglobigerina alabamensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Parvularugoglobigerina eugubina") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Pearsonites anapetes") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Pearsonites broedermanni") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Pearsonites lodoensis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Planoglobanomalina pseudoalgeriana") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Planorotalites capdevilensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Planorotalites pseudoscitula") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Praemurica inconstans") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Praemurica pseudoinconstans") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Praemurica taurica") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Praemurica uncinata") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Praeorbulina circularis") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Praeorbulina curva") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Praeorbulina glomerosa") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Praeorbulina sicanus") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Protentella nicobarensis") ts$ecogroup[i] <- "6" else
    	if (ts$species[i] == "Protentella prolixa") ts$ecogroup[i] <- "6" else
    	if (ts$species[i] == "Protentelloides dalhousiei") ts$ecogroup[i] <- "6" else
    	if (ts$species[i] == "Protentelloides primitiva") ts$ecogroup[i] <- "6" else
    	if (ts$species[i] == "Pseudoglobigerinella bolivariana") ts$ecogroup[i] <- "6" else
    	if (ts$species[i] == "Pseudohastigerina micra") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Pseudohastigerina naguewichiensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Pseudohastigerina sharkriverensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Pseudohastigerina wilcoxensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Pulleniatina finalis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Pulleniatina obliquiloculata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Pulleniatina praecursor") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Pulleniatina praespectabilis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Pulleniatina primalis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Pulleniatina spectabilis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Rectoguembelina cretacea") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Riveroinella martinezpicoi") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Sphaeroidinella dehiscens") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Sphaeroidinella excavata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Sphaeroidinellopsis disjuncta") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Sphaeroidinellopsis kochi") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Sphaeroidinellopsis paenedehiscens") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Sphaeroidinellopsis seminulina") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Streptochilus globigerum") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Streptochilus globulosum") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Streptochilus latum") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Streptochilus martini") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Streptochilus pristinum") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Subbotina angiporoides") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina cancellata") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina corpulenta") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina crociapertura") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Subbotina eocaena") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Subbotina gortanii") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Subbotina hornibrooki") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina jacksonensis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina linaperta") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina patagonica") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Subbotina roesnaesensis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina senni") ts$ecogroup[i] <- "5" else
    	if (ts$species[i] == "Subbotina sp1") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina sp2") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina triangularis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Subbotina triloculinoides") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina trivialis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina utilisindex") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Subbotina velascoensis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Subbotina yeguaensis") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Tenuitella angustiumbilicata") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Tenuitella clemenciae") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Tenuitella fleisheri") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Tenuitella gemma") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Tenuitella insolita") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Tenuitella iota") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Tenuitella minutissima") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Tenuitella munda") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Tenuitella neobrevispira") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Tenuitella parkerae") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Tenuitella patefacta") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Tenuitella praegemma") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Trilobatus bisphericus") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Trilobatus primordius") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Trilobatus sacculifer") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Trilobatus trilobus") ts$ecogroup[i] <- "1" else
    	if (ts$species[i] == "Truncorotalia cavernula") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia crassaconica") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia crassaformis") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia crassula") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia excelsa") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia hessi") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia oceanica") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia pachytheca") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia ronda") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia tenuitheca") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia tosaensis") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia truncatulinoides") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Truncorotalia viola") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Turborotalia altispiroides") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalia ampliapertura") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalia cerroazulensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalia cocoaensis") ts$ecogroup[i] <- "3" else
    	if (ts$species[i] == "Turborotalia cunialensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalia frontosa") ts$ecogroup[i] <- "4" else
    	if (ts$species[i] == "Turborotalia increbescens") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalia pomeroli") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalia possagnoensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalita carcoselleensis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalita clarkei") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalita cristata") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalita humilis") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalita praequinqueloba") ts$ecogroup[i] <- "2" else
    	if (ts$species[i] == "Turborotalita quinqueloba") ts$ecogroup[i] <- "5" else
    	if (ts$species[i] == "Woodringina claytonensis") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Zeauvigerina aegyptiaca") ts$ecogroup[i] <- "NA" else
    	if (ts$species[i] == "Zeauvigerina waiparaensis") ts$ecogroup[i] <- "NA	" 
}

#Let's call this something new, we will come back to it a little later                                            
                                             
write_csv(ts, "Triton_Ecogroups.csv")
