#Load packspeciess
library(tidyverse)

#Change the dataset name to "df" to make things a little less messy

df <- triton.trim2

#Add a new column with the header "ecogroup"

df["ecogroup"] <- NA

#Assign each species to it's ecogroup

for (i in 1:(nrow(df))) {
    	if (df$species[i] == "Acarinina africana") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina alticonica") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina angulosa") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina aspensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina boudreauxi") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina bullbrooki") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina coalingensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina collactea") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina cuneicamerata") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina echinata") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina esnaensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina esnehensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina interposita") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina mcgowrani") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina mckannai") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina medizzai") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina nitida") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina pentacamerata") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina praetopilensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina primitiva") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina pseudosubsphaerica") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina pseudotopilensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina punctocarinata") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina quetra") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina rohri") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina sibaiyaensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina soldadoensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina strabocella") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina subsphaerica") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina topilensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Acarinina wilcoxensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Alicantina lozanoi") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Astrorotalia palmerae") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Beella digitata") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Beella digitata") df$ecogroup[i] <- "NA" else
    	if (df$species[i] == "Beella megastoma") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Beella praedigitata") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Berggrenia pumilio") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Candeina nitida") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Cassigerinella chipolensis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Cassigerinella eocaenica") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Cassigerinelloita amekiensis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Catapsydrax africanus") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Catapsydrax dissimilis") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Catapsydrax globiformis") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Catapsydrax howei") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Catapsydrax parvulus") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Catapsydrax unicavus") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Chiloguembelina crinita") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Chiloguembelina cubensis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Chiloguembelina midwayensis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Chiloguembelina morsei") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Chiloguembelina ototara") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Chiloguembelina parallela") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Chiloguembelina subtriangularis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Chiloguembelina trinitatensis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Chiloguembelina wilcoxensis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Ciperoella angulisuturalis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Ciperoella ciperoensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Clavatorella bermudezi") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Clavigerinella akersi") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Clavigerinella caucasica") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Clavigerinella colombiana") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Clavigerinella eocanica") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Clavigerinella jarvisi") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Cribrohantkenina inflata") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Dentigloborotalia anfracta") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Dentoglobigerina altispira") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Dentoglobigerina baroemoenensis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Dentoglobigerina binaiensis") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Dentoglobigerina galavisi") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Dentoglobigerina globosa") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Dentoglobigerina globularis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Dentoglobigerina juxtabinaiensis") df$ecogroup[i] <- "NA" else
    	if (df$species[i] == "Dentoglobigerina larmeui") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Dentoglobigerina prasaepis") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Dentoglobigerina pseudovenezuelana") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Dentoglobigerina rohri") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Dentoglobigerina sellii") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Dentoglobigerina sp") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Dentoglobigerina tapuriensis") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Dentoglobigerina tripartita") df$ecogroup[i] <- "NA" else
    	if (df$species[i] == "Dentoglobigerina venezuelana") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Dipsidripella danvillensis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Eoglobigerina edita") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Eoglobigerina eobulloides") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Eoglobigerina spiralis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Fohsella fohsi") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Fohsella lenguaensis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Fohsella lobata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Fohsella paralenguaensis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Fohsella peripheroacuta") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Fohsella peripheroronda") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Fohsella praefohsi") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Fohsella robusta") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globanomalina archeocompressa") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globanomalina australiformis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globanomalina chapmani") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globanomalina compressa") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globanomalina ehrenbergi") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globanomalina imitata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globanomalina luxorensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globanomalina ovalis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globanomalina planocompressa") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globanomalina planoconica") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globanomalina pseudomenardii") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globigerina bulloides") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globigerina eamesi") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerina falconensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerina officinalis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerina umbilicata") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinatella insueta") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Globigerinatella sp.") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Globigerinatheka barri") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinatheka curryi") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinatheka euganea") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinatheka index") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinatheka korotkovi") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinatheka kugleri") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinatheka luterbacheri") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinatheka mexicana") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinatheka semiinvoluta") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinatheka subconglobata") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinatheka tropicalis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinella adamsi") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Globigerinella calida") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globigerinella navazuelensis") df$ecogroup[i] <- "NA" else
    	if (df$species[i] == "Globigerinella obesa") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globigerinella praesiphonifera") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globigerinella radians") df$ecogroup[i] <- "NA" else
    	if (df$species[i] == "Globigerinella siphonifera") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globigerinita glutinata") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Globigerinita minuta") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Globigerinita parkerae") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Globigerinita uvula") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Globigerinoides altiapertura") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides conglobatus") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides diminutus") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides elongatus") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides extremus") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides mitra") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides obliquus") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides parawoodi") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides ruber") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides ruber (pink)") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides ruber (white)") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides seigliei") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoides subquadratus") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globigerinoidesella fistulosa") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globoconella conoidea") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globoconella conomiozea") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globoconella inflata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globoconella miozea") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globoconella pliozea") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globoconella puncticulata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globoconella sphericomiozea") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globoconella terminalis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globoconusa daubjergensis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Globoquadrina conglomerata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globoquadrina dehiscens") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globorotalia flexuosa") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globorotalia merotumida") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globorotalia plesiotumida") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globorotalia tumida") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globorotalia ungulata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globorotalia zealandica") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Globorotaloides eovariabilis") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Globorotaloides hexagonus") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Globorotaloides quadrocameratus") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Globorotaloides stainforthi") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Globorotaloides suteri") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Globorotaloides testarugosa") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Globorotaloides variabilis") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Globoturborotalita anguliofficinalis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globoturborotalita apertura") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globoturborotalita bassriverensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globoturborotalita bollii") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globoturborotalita brazieri") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globoturborotalita cancellata") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globoturborotalita connecta") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globoturborotalita decoraperta") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globoturborotalita druryi") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globoturborotalita euapertura") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Globoturborotalita gnaucki") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globoturborotalita kennetti") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globoturborotalita labiacrassata") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globoturborotalita martini") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globoturborotalita nepenthes") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globoturborotalita occlusa") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globoturborotalita ouachitaensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Globoturborotalita rubescens") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globoturborotalita tenella") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Globoturborotalita woodi") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Guembelitria cretacea") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Guembelitrioides nuttalli") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Hantkenina alabamensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Hantkenina australis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Hantkenina compressa") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Hantkenina dumblei") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Hantkenina lehneri") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Hantkenina liebusi") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hantkenina mexicana") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hantkenina nanggulanensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Hantkenina primitiva") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Hantkenina singanoae") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Hastigerina pelagica") df$ecogroup[i] <- "NA" else
    	if (df$species[i] == "Hirsutella bermudezi") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella challengeri") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella cibaoensis") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella evoluta") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella gigantea") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella hirsuta") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella juanai") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella margaritae") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella praemargaritae") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella praescitula") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella primitiva") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella scitula") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Hirsutella theyeri") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Igorina albeari") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Igorina pusilla") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Igorina tadjikistanensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Jenkinsina triseriata") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Menardella archeomenardii") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Menardella exilis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Menardella fimbriata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Menardella limbata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Menardella menardii") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Menardella miocenica") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Menardella multicamerata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Menardella pertenuis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Menardella praemenardii") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Menardella pseudomiocenica") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Morozovella acuta") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella acutispira") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella aequa") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella allisonensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella angulata") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella apanthesma") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella aragonensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella caucasica") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella conicotruncata") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella crater") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella edgari") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella formosa") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella gracilis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella lensiformis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella marginodentata") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella occlusa") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella pasionensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella praeangulata") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella subbotinae") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovella velascoensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovelloides bandyi") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovelloides coronatus") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovelloides crassatus") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Morozovelloides lehneri") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Muricohedbergella holmdelensis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Muricohedbergella monmouthensis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Mutabella mirabilis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Neogloboquadrina acostaensis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Neogloboquadrina dutertrei") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Neogloboquadrina humerosa") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Neogloboquadrina incompta") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Neogloboquadrina pachyderma") df$ecogroup[i] <- "5" else
    	if (df$species[i] == "Orbulina suturalis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Orbulina universa") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Orbulinoides beckmanni") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Orcadia riedeli") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Paragloborotalia acrostoma") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Paragloborotalia bella") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Paragloborotalia birnageae") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Paragloborotalia continuosa") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Paragloborotalia griffinoides") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Paragloborotalia incognita") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Paragloborotalia kugleri") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Paragloborotalia mayeri") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Paragloborotalia nana") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Paragloborotalia opima") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Paragloborotalia pseudocontinuosa") df$ecogroup[i] <- "NA" else
    	if (df$species[i] == "Paragloborotalia pseudokugleri") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Paragloborotalia semivera") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Paragloborotalia siakensis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Parasubbotina aff_pseudobulloides") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Parasubbotina eoclava") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Parasubbotina griffinae") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Parasubbotina hagni") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Parasubbotina inaequispira") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Parasubbotina prebetica") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Parasubbotina pseudobulloides") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Parasubbotina pseudowilsoni") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Parasubbotina varianta") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Parasubbotina variospira") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Parvularugoglobigerina alabamensis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Parvularugoglobigerina eugubina") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Pearsonites anapetes") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Pearsonites broedermanni") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Pearsonites lodoensis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Planoglobanomalina pseudoalgeriana") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Planorotalites capdevilensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Planorotalites pseudoscitula") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Praemurica inconstans") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Praemurica pseudoinconstans") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Praemurica taurica") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Praemurica uncinata") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Praeorbulina circularis") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Praeorbulina curva") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Praeorbulina glomerosa") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Praeorbulina sicanus") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Protentella nicobarensis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Protentella prolixa") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Protentelloides dalhousiei") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Protentelloides primitiva") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Pseudoglobigerinella bolivariana") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Pseudohastigerina micra") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Pseudohastigerina naguewichiensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Pseudohastigerina sharkriverensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Pseudohastigerina wilcoxensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Pulleniatina finalis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Pulleniatina obliquiloculata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Pulleniatina praecursor") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Pulleniatina praespectabilis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Pulleniatina primalis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Pulleniatina spectabilis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Rectoguembelina cretacea") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Riveroinella martinezpicoi") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Sphaeroidinella dehiscens") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Sphaeroidinella excavata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Sphaeroidinellopsis disjuncta") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Sphaeroidinellopsis kochi") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Sphaeroidinellopsis paenedehiscens") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Sphaeroidinellopsis seminulina") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Streptochilus globigerum") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Streptochilus globulosum") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Streptochilus latum") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Streptochilus martini") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Streptochilus pristinum") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Subbotina angiporoides") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina cancellata") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina corpulenta") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina crociapertura") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Subbotina eocaena") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Subbotina gortanii") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Subbotina hornibrooki") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina jacksonensis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina linaperta") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina patagonica") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Subbotina roesnaesensis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina senni") df$ecogroup[i] <- "5" else
    	if (df$species[i] == "Subbotina sp1") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina sp2") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina triangularis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Subbotina triloculinoides") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina trivialis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina utilisindex") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Subbotina velascoensis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Subbotina yeguaensis") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Tenuitella angustiumbilicata") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Tenuitella clemenciae") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Tenuitella fleisheri") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Tenuitella gemma") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Tenuitella insolita") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Tenuitella iota") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Tenuitella minutissima") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Tenuitella munda") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Tenuitella neobrevispira") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Tenuitella parkerae") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Tenuitella patefacta") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Tenuitella praegemma") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Trilobatus bisphericus") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Trilobatus primordius") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Trilobatus sacculifer") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Trilobatus trilobus") df$ecogroup[i] <- "1" else
    	if (df$species[i] == "Truncorotalia cavernula") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia crassaconica") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia crassaformis") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia crassula") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia excelsa") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia hessi") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia oceanica") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia pachytheca") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia ronda") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia tenuitheca") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia tosaensis") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia truncatulinoides") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Truncorotalia viola") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Turborotalia altispiroides") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalia ampliapertura") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalia cerroazulensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalia cocoaensis") df$ecogroup[i] <- "3" else
    	if (df$species[i] == "Turborotalia cunialensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalia frontosa") df$ecogroup[i] <- "4" else
    	if (df$species[i] == "Turborotalia increbescens") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalia pomeroli") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalia possagnoensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalita carcoselleensis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalita clarkei") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalita cristata") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalita humilis") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalita praequinqueloba") df$ecogroup[i] <- "2" else
    	if (df$species[i] == "Turborotalita quinqueloba") df$ecogroup[i] <- "5" else
    	if (df$species[i] == "Woodringina claytonensis") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Zeauvigerina aegyptiaca") df$ecogroup[i] <- "6" else
    	if (df$species[i] == "Zeauvigerina waiparaensis") df$ecogroup[i] <- "6" 
}
                                            
write.csv(df, paste(file = "Triton_Ecogroups.csv"))
